socialapp/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required

from . import views
from . import api

app_name = 'socialapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('profile_list/', login_required(login_url='/account/login')(views.ProfileList.as_view()), name='profile_list'),
    path('profile_detail/<int:pk>', views.profile_detail, name='profile_detail'),
    path('profile_detail/<int:pk>/image_gallery', views.image_gallery, name='image_gallery'),
    path('account/', include('django.contrib.auth.urls')),
    path('account/register', views.register, name='register'),
    path('api/image', api.ImageDetail.as_view(), name='image_api'),
    path('api/images/<int:pk>', api.ImageList.as_view(), name='images_api'),
    path('chat/', views.chatIndex, name='chat_index'),
    path('chat/<str:room_name>/', views.chatRoom, name='chat_room')
] 

socialnetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('socialapp.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

socialapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    follows = models.ManyToManyField('self', related_name='followed_by', symmetrical=False, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance) #user field of Profile is the instance of the signal Sender
        user_profile.save()
        user_profile.follows.add(instance.profile)
        user_profile.save()


class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.DO_NOTHING)
    body = models.CharField(max_length=256)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return (
            f"{self.user} "
            f"{self.created_at}"
            f"{self.body[:20]}"
        )


class Image(models.Model):
    name = models.CharField(max_length=256, unique=True, db_index=True)
    image = models.ImageField(blank=False)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Message(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username

        

socialapp/forms.py
from django import forms

from .models import *

class PostForm(forms.ModelForm):
    body = forms.CharField(max_length=256, 
        required=True,
        widget=forms.widgets.Textarea(
            attrs={
                "placeholder": "post something here..."
            }
        ),
        label=""
    )
    class Meta:
        model = Post
        exclude = ('user',)


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta:
        model = User
        fields = ['username', 'password']

    

socialapp/views.py
import json
from django.utils.safestring import mark_safe
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView

from .models import *
from .forms import *

@login_required(login_url='/account/login')
def index(request):
    form = PostForm(request.POST or None)
    followed_posts = Post.objects.filter(user__profile__in=request.user.profile.follows.all()).order_by('-created_at')
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False) # not save the record in db yet
            post.user = request.user
            post.save()
            return redirect("socialapp:index")
    return render(request, 'socialapp/index.html', {
        'form': form,
        'followed_posts': followed_posts,
    })

class ProfileList(ListView):
    model = Profile
    template_name = 'socialapp/profile_list.html'
    context_object_name = 'profiles'

    def get_queryset(self):
        try:
            s = self.request.GET.get('profile')
        except KeyError:
            s = None
        if s:
            profiles = Profile.objects.filter(user__username__icontains=s)
        else:
            profiles = Profile.objects.exclude(user=self.request.user)
        return profiles


@login_required(login_url='/account/login')
def profile_detail(request, pk):
    profile = Profile.objects.get(pk=pk)
    if request.method == 'POST':
        current_profile_user = request.user.profile
        action = request.POST['followBtn']
        if action == 'follow':
            current_profile_user.follows.add(profile)
        elif action == 'unfollow':
            current_profile_user.follows.remove(profile)
        current_profile_user.save()
    return render(request, 'socialapp/profile_detail.html', {
        'profile': profile,
    })


@login_required(login_url='/account/login')
def image_gallery(request, pk):
    profile = Profile.objects.get(pk=pk)
    profile_id = json.dumps(profile.id)
    return render(request, 'socialapp/image_gallery.html', {
        'profile_id': profile_id
    })

def register(request):
    user_form = UserForm(request.POST or None)
    if request.method == 'POST':
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            return redirect('login/')    
        else:
            return render(request, 'registration/register.html', {
                'user_form': user_form
            })        
    return render(request, 'registration/register.html', {
        'user_form': user_form
    })  

@login_required(login_url='/account/login')
def chatIndex(request):
    return render(request, 'chat/index.html')

@login_required(login_url='/account/login')
def chatRoom(request, room_name):
    return render(request, 'chat/room.html', {
        'room_name': room_name,
        'username': mark_safe(json.dumps(request.user.username)),
    })

socialapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'socialapp/style.css' %}">
    <title>Social Network</title>
</head>
<body>
    <div id="root">
        <div id="header">
            <div id='nav-container'>
                {% if user.is_authenticated %}
                    <a href="{% url 'socialapp:logout' %}">Logout</a>
                {% else %}
                    <a href="{% url 'socialapp:register' %}">Register</a>
                    <a href="{% url 'socialapp:login' %}">Login</a>
                {% endif %}
            </div>
            <div id="intro">
                <a href="{% url 'socialapp:index' %}">
                    <h2>Social Network</h2>
                </a>
                <h4>My little social network application built with Django.</h4>
            </div>
        </div>
        
        {% if user.is_authenticated %}
            <div id="content">
                {% block content %}
                {% endblock content %}
            </div>
        {% else %}
            <div id="account">
                {% block account %}
                {% endblock %}
            </div>
        {% endif %}
    </div>
</body>
</html>

socialapp/templates/chat/index.html
{% extends '../base.html' %}

{% block content %}
    <h2>What chat romm would you like to enter?</h2>
    <input type="text" id="room-name-input" size="100">
    <br>
    <input type="button" id="room-name-submit" value="Enter">
    <script>
        const input = document.querySelector('#room-name-input')
        const submitBtn = document.querySelector('#room-name-submit')
        input.focus()
        input.onkeyup = function(e) {
            if (e.key === 'Enter') {
                submitBtn.click()
            }
        }
        submitBtn.onclick = function(e) {
            const chatroom = input.value
            window.location.pathname = '/chat/' + chatroom + '/' 
        }
    </script>
{% endblock %}

socialapp/templates/chat/room.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'chat/room.css' %}">
    <ul id="chat-log">
        <li class="sent">
        </li>
        <li class="replies">
        </li>
    </ul>
    <br>
    <input type="text" id="chat-message-input" size="100"><br>
    <input type="submit" id="chat-message-submit" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.querySelector('#room-name').textContent)
        const username = {{ username }}
        const chatSocket = new WebSocket(
            'ws://' 
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        )

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data)
            document.querySelector('#chat-log').value += (data.data.content + '\n')
            createMessage(data)
        }

        chatSocket.onclose = function(e) {
            console.log("Chat socket closed unexpectedly.")
        }

        const msgInput = document.querySelector('#chat-message-input')
        const msgSubmit = document.querySelector('#chat-message-submit')

        msgInput.focus()
        msgInput.onkeyup = function(e) {
            if (e.key === 'Enter') {
                msgSubmit.click()
            }
        }

        msgSubmit.onclick = function(e) {
            const message = document.querySelector('#chat-message-input').value
            chatSocket.send(JSON.stringify({
                'message': message,
                'from': username,
            }))
            document.querySelector('#chat-message-input').value = ''
        }

        function createMessage(data) {
            let author = data.data.author
            let msgListTag = document.createElement('li')
            let imgTag = document.createElement('img')
            let pTag = document.createElement('p')
            pTag.textContent = data.data.content
            imgTag.src = '/images/profile-pic.jpeg'
            imgTag.alt = 'profile-pic'
            imgTag.width = 40
            imgTag.height = 40
            if (author === username) {
                msgListTag.className = 'replies'
            } else {
                msgListTag.className = 'sent'
            }
            msgListTag.appendChild(imgTag)
            msgListTag.appendChild(pTag)
            document.querySelector('#chat-log').appendChild(msgListTag)
        }
    </script>

{% endblock %}

socialapp/templates/socialapp/image_gallery.html
{% extends "../base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'socialapp/image_gallery.css' %}" >
<div id="image-gallery-container">
    <h3>Upload Images</h3>
    <form class="image-form" action="/api/image" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">Image Name:</label>
        <input type="text" name="name">
        <br/><br/>
        <label for="image">Upload Image:</label>
        <input type="file" name="image" accept="image/*">
        <br/><br/>
        <input type="hidden" name="profile_id" value="{{ profile_id}}">
        <input type="submit" value="Upload">
    </form>
    <h3 id="gallery-title">Image Gallery</h3>
    <div class="image-container">
    </div>
    {{ profile_id|json_script:"profile_id" }}
</div>
<script src="/static/js/index.js">
</script>

{% endblock %}

socialapp/templates/socialapp/index.html
{% extends '../base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'socialapp/index.css' %}">
    <div class="content-header">
        <h4>Logged in User: {{ user.username }}</h4>
        <div id='profile-btn'>
            <a href="{% url 'socialapp:profile_list' %}">
                <button>All Profiles</button>
            </a>
            <a href="{% url 'socialapp:profile_detail' request.user.profile.id %}">
                <button>My Profile</button>
            </a>
        </div>
    </div>
    
    {% for post in followed_posts %}
        <p class="post">{{ post.body }} - created at: {{ post.created_at }} - by {{ post.user.username }}</p>
    {% endfor %}

    <div class="post-form">
        <h4>POST FORM</h4>
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Post</button>
        </form>
    </div>
{% endblock %}

socialapp/templates/socialapp/profile_detail.html
{% extends "../base.html" %}
{% load static %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'socialapp/detail.css' %}">
    <div class="profile">
        <div class="header-container">
            <h3>{{ profile.user.username|upper }}</h3>
            <div class="btn-container">
                <form action="" method="POST" enctype="application/x-www-form-urlencoded">
                    {% csrf_token %}
                    {% if profile in user.profile.follows.all %}
                        <button type="submit" name="followBtn" value="follow" disabled>Follow</button>
                        <button type="submit" name="followBtn" value="unfollow">Unfollow</button>
                    {% else %}
                        <button type="submit" name="followBtn" value="follow">Follow</button>
                        <button type="submit" name="followBtn" value="unfollow" disabled>Unfollow</button>
                    {% endif %}
                </form>
                {% if user.username != profile.user.username %}
                    <button id="chat-btn"><a href="/chat/lobby">Chat</a></button>
                {% endif %}
            </div> 
        </div>
        
        <h3 id="posts">Posts:</h3>
        <div class="posts">
            {% for post in profile.user.posts.all %}
            <div class="post-container">
                {{ post.body }} - 
                <span>
                    created at: {{ post.created_at }}
                </span>
            </div>
            {% endfor %}
        </div>
        <div id="follow-container">
            <div id="following-list">
                <h3>Following:</h3>
                <ol>
                    {% for following in profile.follows.all %}
                        <li>{{ following.user.username }}</li>
                    {% endfor %}
                </ol>
            </div>
            <div id="followed-list">
                <h3>Followed by:</h3>
                <ol>
                    {% for followed in profile.followed_by.all %}
                        <li>{{ followed.user.username }}</li>
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>
    <br>
    <h3>
        <a href="/profile_detail/{{ profile.id }}/image_gallery">View Image Gallery</a>
    </h3>
{% endblock %}

socialapp/templates/socialapp/profile_list.html
{% extends "../base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'socialapp/profile-list.css' %}">
<h3>Search Profiles</h3>
<form action="{% url 'socialapp:profile_list' %}" method="GET">
    <input type="text" name="profile" value="{{ request.GET.profile }}">
    <input type="submit" value="Search">
</form>

<h3>Results</h3>
{% for profile in profiles %}
    <div class="profile_container">
        <p>{{ profile.user.username }}</p>
        <a href="/profile_detail/{{ profile.id }} ">
            @{{ profile.user.username|lower }}
        </a>
    </div>
{% endfor %}

{% endblock%}